### ISSUE TITLE
Allow for literals in mixfix expression

### ISSUE THREAD

**Issue by vitvly** [awto/mixfix-clj#3]
Hi!

Do you think it is feasible to extend the definition of `%` macro somewhat, in order to allow for literal expressions in expression body? For instance, this expression throws `CompilerException java.lang.ClassCastException: java.lang.Long cannot be cast to clojure.lang.IFn`:

```
(m/% 5)
```

By changing the definition of the `%` macro to

```
(defmacro % [& args] 
  (if (next args) 
    `(%/% ~@args)
    (first args)))
```

this issue seems to be solved. What do you think?

**Comment by awto** [comment]
Hi, sorry for late response,

I don't know really, the macro is to be transformed into call, so (m/% 5) should be equivalent to (5), 
and that of course isn't correct. If we change the macro this way it would convert (m/% f) to just f, while the intention could be to call that f without arguments.
If your task is just parsing the string you can transform your form into clojure sequence and interpret it in any way you wish, e.g. checking if it has just 1 element and return it if it is or call the resulting form otherwise.

**Comment by vitvly** [comment]
Hi,

thanks for reply. I see now - single literal expressions can be transformed to `(identity val)` before feeding them to `%` macro. Thanks for advice!
